name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2

        - name: Use Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '18'
            registry-url: 'https://npm.pkg.github.com'

        - name: Install dependencies
          run: npm ci

        - name: Lint
          run: npm run lint

        - name: Run tests
          run: npm test

        - name: Publish to GitHub Packages
          run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}